---
kind: pipeline
type: docker
name: build

trigger:
  branches:
    - "main_mine"
  event:
    - push

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "android"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'gradle-build-cache'
        - '.gradle'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: build
    image: nexus.semperpax.com:6000/android-build-box:latest
    pull: if-not-exists
    environment:
      GOOGLE_SERVICES:
        from_secret: google-services
    commands:
      - echo "$GOOGLE_SERVICES" > app/google-services.json
      - bash ./gradlew --build-cache assemblePlayRelease

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "android"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'gradle-build-cache'
        - '.gradle'
    volumes:
    - name: cache
      path: /tmp/cache

volumes:
- name: cache
  host:
    path: /tmp/drone/cache
---
kind: pipeline
type: docker
name: release

trigger:
  branches:
    - "main_mine"
  event:
    - tag

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "android"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'gradle-build-cache'
        - '.gradle'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: build
    image: nexus.semperpax.com:6000/android-build-box:latest
    pull: if-not-exists
    environment:
      GOOGLE_SERVICES:
        from_secret: google-services
    commands:
      - echo "$GOOGLE_SERVICES" > app/google-services.json
      - ./gradlew --build-cache assemblePlayRelease

  - name: sign
    image: nexus.semperpax.com:6000/android-build-box:latest
    pull: if-not-exists
    environment:
      SEMPERPAX_KEYSTORE:
        from_secret: semperpax-keystore
      SEMPERPAX_KEYSTORE_PASSWORD:
        from_secret: semperpax-keystore-password
    commands:
      - echo "$SEMPERPAX_KEYSTORE" | base64 -d > /tmp/keystore
      - $ANDROID_SDK_HOME/build-tools/30.0.0/apksigner sign -ks /tmp/keystore --ks-pass env:SEMPERPAX_KEYSTORE_PASSWORD --ks-key-alias androiddebugkey app/build/outputs/apk/play/release/app-play-release-unsigned.apk
      - mv app/build/outputs/apk/play/release/app-play-release-unsigned.apk app/build/outputs/apk/play/release/ntfy-play-release.apk

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea-apikey
      base_url: https://git.semperpax.com
      files: app/build/outputs/apk/play/release/*.apk

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "android"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'gradle-build-cache'
        - '.gradle'
    volumes:
    - name: cache
      path: /tmp/cache

volumes:
- name: cache
  host:
    path: /tmp/drone/cache