---
kind: pipeline
type: docker
name: build

trigger:
  branches:
    - "main_mine"
  event:
    - push

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "android"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - '~/.gradle/wrapper'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: build
    image: nexus.semperpax.com:6000/android-build-box:latest
    pull: if-not-exists
    commands:
      - bash ./gradlew assemblePlayRelease
      - make drone-cache

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "android"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - '~/.gradle/wrapper'
    volumes:
    - name: cache
      path: /tmp/cache

volumes:
- name: cache
  host:
    path: /tmp/drone/cache